lebensmittel <- c("rewe sagt", "denns biomarkt", "steinecke s")
auswaerts_essen <- c("babo sushi")
drogerie <- c("dm fil")
auto <- c("bp tankstelle", "adeg 1093", "ah nempitz", "shell 6872", "shell 2404")
medizin <- c("steinbock apotheke")
strom <- c("evd energieversorgung")
urlaub <- c("erlebnisberg nagelkoepfel", "tauern spa")
geschenke <- c("gefeko berlin")
kinder <- c("tierpark berlin", "berliner instit", "bezirksamt friedrichshain")
internet <- c("tele columbus")