lebensmittel <- c("rewe sagt", "denns biomarkt", "steinecke s", 'edeka 5416', 'konsum leipzig', 'norma sagt', 'mein markt', 'aldi sagt', 'netto aps')
auswaerts_essen <- c("babo sushi")
drogerie <- c("dm fil")
auto <- c("bp tankstelle", "adeg 1093", "ah nempitz", "shell 6872", "shell 2404", 'jet dankt', 'adac autoversicherung', 'shell 3699',
          'jet-tankstelle', 'allg.deutscher')
medizin <- c("steinbock apotheke", 'apotheke im')
strom <- c("evd energieversorgung")
urlaub <- c("erlebnisberg nagelkoepfel", "tauern spa")
geschenke <- c("gefeko berlin")
kinder <- c("tierpark berlin", "berliner instit", "bezirksamt friedrichshain", 'shoe4you gmbh', 'mytoys.de')
internet <- c("tele columbus", 'telekom deutschland')
miete <- c('varenta immobilienservice')
sparen <- c('dkb ag')
wohnung <- c('rundfunk ard')
baumarkt <- c('toom bm', 'der hollaender')