lebensmittel <- c("rewe sagt", "denns biomarkt", "steinecke s", 'edeka 5416', 'konsum leipzig')
auswaerts_essen <- c("babo sushi")
drogerie <- c("dm fil")
auto <- c("bp tankstelle", "adeg 1093", "ah nempitz", "shell 6872", "shell 2404", 'jet dankt', 'adac autoversicherung', 'shell 3699')
medizin <- c("steinbock apotheke", 'apotheke im')
strom <- c("evd energieversorgung")
urlaub <- c("erlebnisberg nagelkoepfel", "tauern spa")
geschenke <- c("gefeko berlin")
kinder <- c("tierpark berlin", "berliner instit", "bezirksamt friedrichshain", 'shoe4you gmbh')
internet <- c("tele columbus")
miete <- c('varenta immobilienservice')
sparen <- c('dkb ag')
wohnung <- c('rundfunk ard')
baumarkt <- c('toom bm')